/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Coleccion;
import modelo.Cliente;
import modelo.Evento;
import modelo.Fiesta;
import modelo.Matrimonio;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import modelo.PaqueteEvento;
/**
 *
 * @author GOLDEN GAMERS
 */

public class RegistroClienteEvento extends javax.swing.JFrame {

    Coleccion col = new Coleccion();
    /**
     * Creates new form RegistroEvento
     */
    public RegistroClienteEvento() {
        initComponents();
        listarDatosClientes();
        listarDatosPaqueteEvento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        txtRut = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonAgregarCliente = new javax.swing.JButton();
        jButtonListarCliente = new javax.swing.JButton();
        jButtonLimpiarCampos = new javax.swing.JButton();
        jButtonBuscarCliente = new javax.swing.JButton();
        jButtonEliminarCliente = new javax.swing.JButton();
        txtBuscarCliente = new javax.swing.JTextField();
        txtEliminarCliente = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jButtonModificarRut = new javax.swing.JButton();
        jButtonModificarNombre = new javax.swing.JButton();
        jButton7ModificarCorreo = new javax.swing.JButton();
        jButtonModificarTelefono = new javax.swing.JButton();
        txtModificarTelefono = new javax.swing.JTextField();
        txtModificarCorreo = new javax.swing.JTextField();
        txtModificarNombreCliente = new javax.swing.JTextField();
        txtModificarRut = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtTiempoCantPlatos = new javax.swing.JTextField();
        txtMusicaEnVivo = new javax.swing.JTextField();
        txtMatriDesEveneto = new javax.swing.JTextField();
        txtMatriCantAsistentes = new javax.swing.JTextField();
        txtMatriTamanioRecinto = new javax.swing.JTextField();
        txtMatriCantMesas = new javax.swing.JTextField();
        txtMatriPrecio = new javax.swing.JTextField();
        jButton7AgregarMatrimonio = new javax.swing.JButton();
        jButtonListarEventoMatri = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        txtMatriTipoEvento = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        txtConOsinAlcohol = new javax.swing.JTextField();
        txtNroDjs = new javax.swing.JTextField();
        txtDesEveneto = new javax.swing.JTextField();
        txtCantidadAsistentes = new javax.swing.JTextField();
        txtTamanioRecinto = new javax.swing.JTextField();
        txtCantidadMesas = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jButtonAgregarFiesta = new javax.swing.JButton();
        jButtonListarEvento = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtTipoEvento = new javax.swing.JTextField();
        jButtonEliminarPaqEventoFiesta = new javax.swing.JButton();
        txtEliminarPaqEventFiesta = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtEventoSeleccionado = new javax.swing.JTextField();
        txtClienteEventoSolicitado = new javax.swing.JTextField();
        txtFechaHora = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButtonAgregarEventoSolicitado = new javax.swing.JButton();
        jButtonListarEventoSolicitado = new javax.swing.JButton();
        jButtonEliminarEventoSolicitado = new javax.swing.JButton();
        txtEliminarEveFechaHora = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EventGreat");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("REGISTRO CLIENTE");

        jLabel2.setText("Rut (sin puntos/ con guion y DV)");

        jLabel3.setText("Nombre Completo");

        jLabel4.setText("Correo");

        jLabel5.setText("Telefono");

        txtRut.setText("Ingresa 9 o 10 caracter");
        txtRut.setToolTipText("testttt");

        txtTelefono.setText("0");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonAgregarCliente.setText("AGREGAR");
        jButtonAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarClienteActionPerformed(evt);
            }
        });

        jButtonListarCliente.setText("LISTAR");
        jButtonListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarClienteActionPerformed(evt);
            }
        });

        jButtonLimpiarCampos.setText("LIMPIAR");
        jButtonLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarCamposActionPerformed(evt);
            }
        });

        jButtonBuscarCliente.setText("BUSCAR POR RUT");
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });

        jButtonEliminarCliente.setText("ELIMINAR POR RUT");
        jButtonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarClienteActionPerformed(evt);
            }
        });

        txtEliminarCliente.setText("0");

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jButtonModificarRut.setText("Modificar rut");
        jButtonModificarRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarRutActionPerformed(evt);
            }
        });

        jButtonModificarNombre.setText("Modificar nombre");
        jButtonModificarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarNombreActionPerformed(evt);
            }
        });

        jButton7ModificarCorreo.setText("Modificar Correo");
        jButton7ModificarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ModificarCorreoActionPerformed(evt);
            }
        });

        jButtonModificarTelefono.setText("Modificar Telefono");
        jButtonModificarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarTelefonoActionPerformed(evt);
            }
        });

        txtModificarNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificarNombreClienteActionPerformed(evt);
            }
        });

        txtModificarRut.setText("Ingresa 9 o 10 caracter");

        jLabel28.setText("(sin puntos/ con guion y DV)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAgregarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRut)
                            .addComponent(txtNombreCompleto)
                            .addComponent(txtCorreo)
                            .addComponent(txtTelefono))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonListarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpiarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonBuscarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEliminarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel28)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonModificarTelefono)
                                    .addComponent(jButton7ModificarCorreo)
                                    .addComponent(jButtonModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtModificarCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(txtModificarTelefono)
                                    .addComponent(txtModificarNombreCliente, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonModificarRut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(txtModificarRut, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonAgregarCliente)
                    .addComponent(jButtonListarCliente)
                    .addComponent(jButtonLimpiarCampos)
                    .addComponent(jButtonBuscarCliente)
                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminarCliente)
                    .addComponent(txtEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txtNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModificarRut)
                            .addComponent(txtModificarRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModificarNombre)
                            .addComponent(txtModificarNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtModificarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtModificarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton7ModificarCorreo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonModificarTelefono))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("REGISTRO EVENTO MATRIMONIO");

        jLabel15.setText("TiempoMenuCantidadPlatos");

        jLabel16.setText("MusicaEnVivo [true(si)/false(no)]");

        jLabel17.setText("DescripcionEvento");

        jLabel18.setText("CantidadAsistentes");

        jLabel19.setText("TamanioRecinto");

        jLabel20.setText("CantidadMesas");

        jLabel21.setText("Precio");

        txtMusicaEnVivo.setText("Responde true o false");

        txtMatriDesEveneto.setEditable(false);
        txtMatriDesEveneto.setText("matrimonio full");

        txtMatriCantAsistentes.setText("0");

        txtMatriTamanioRecinto.setText("0");

        txtMatriCantMesas.setText("0");

        txtMatriPrecio.setText("0");

        jButton7AgregarMatrimonio.setText("AGREGAR EVENTO");
        jButton7AgregarMatrimonio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7AgregarMatrimonioActionPerformed(evt);
            }
        });

        jButtonListarEventoMatri.setText("LISTAR EVENTO");
        jButtonListarEventoMatri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarEventoMatriActionPerformed(evt);
            }
        });

        jLabel27.setText("Tipo Evento");

        txtMatriTipoEvento.setEditable(false);
        txtMatriTipoEvento.setText("matrimonio");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel27))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTiempoCantPlatos)
                                    .addComponent(txtMusicaEnVivo)
                                    .addComponent(txtMatriDesEveneto)
                                    .addComponent(txtMatriCantAsistentes)
                                    .addComponent(txtMatriTamanioRecinto)
                                    .addComponent(txtMatriCantMesas)
                                    .addComponent(txtMatriPrecio)
                                    .addComponent(txtMatriTipoEvento)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButton7AgregarMatrimonio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonListarEventoMatri))))
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtTiempoCantPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtMusicaEnVivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtMatriTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtMatriDesEveneto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtMatriCantAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtMatriTamanioRecinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtMatriCantMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtMatriPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7AgregarMatrimonio)
                    .addComponent(jButtonListarEventoMatri))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("REGISTRO EVENTO FIESTA");

        jLabel7.setText("DescripcionEvento");

        jLabel8.setText("CantidadAsistentes");

        jLabel9.setText("TamanioRecinto");

        jLabel10.setText("CantidadMesas");

        jLabel11.setText("Precio");

        jLabel13.setText("NumeroDjEnEscena");

        jLabel14.setText("BarAlcohol [true(si)/false(no)]");
        jLabel14.setToolTipText("");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        txtConOsinAlcohol.setText("Responde true o false");

        txtNroDjs.setText("0");

        txtDesEveneto.setEditable(false);
        txtDesEveneto.setText("fiesta 15");

        txtCantidadAsistentes.setText("0");

        txtTamanioRecinto.setText("0");

        txtCantidadMesas.setText("0");

        txtPrecio.setText("0");

        jButtonAgregarFiesta.setText("AGREGAR EVENTO");
        jButtonAgregarFiesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarFiestaActionPerformed(evt);
            }
        });

        jButtonListarEvento.setText("LISTAR EVENTO");
        jButtonListarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarEventoActionPerformed(evt);
            }
        });

        jLabel26.setText("Tipo Evento");

        txtTipoEvento.setEditable(false);
        txtTipoEvento.setText("fiesta");

        jButtonEliminarPaqEventoFiesta.setText("ELIMINAR EVENTO POR ID");
        jButtonEliminarPaqEventoFiesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarPaqEventoFiestaActionPerformed(evt);
            }
        });

        txtEliminarPaqEventFiesta.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButtonAgregarFiesta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonListarEvento))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCantidadMesas)
                                    .addComponent(txtTamanioRecinto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCantidadAsistentes, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDesEveneto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtTipoEvento, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNroDjs)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(txtConOsinAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtPrecio))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonEliminarPaqEventoFiesta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEliminarPaqEventFiesta, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtConOsinAlcohol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtNroDjs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTipoEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtDesEveneto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCantidadAsistentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTamanioRecinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtCantidadMesas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarFiesta)
                    .addComponent(jButtonListarEvento)
                    .addComponent(jButtonEliminarPaqEventoFiesta)
                    .addComponent(txtEliminarPaqEventFiesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("REGISTRO EVENTO SOLICITADO");

        jLabel23.setText("CLIENTE");

        jLabel24.setText("EVENTO SELECCIONADO");

        jLabel25.setText("FECHA Y HORA ");

        txtEventoSeleccionado.setEditable(false);

        txtClienteEventoSolicitado.setEditable(false);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jButtonAgregarEventoSolicitado.setText("Agregar Evento Solicitado");
        jButtonAgregarEventoSolicitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarEventoSolicitadoActionPerformed(evt);
            }
        });

        jButtonListarEventoSolicitado.setText("Listar evento solicitado");
        jButtonListarEventoSolicitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarEventoSolicitadoActionPerformed(evt);
            }
        });

        jButtonEliminarEventoSolicitado.setText("Eliminar Evento Solicitado Por fecha y hora");
        jButtonEliminarEventoSolicitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarEventoSolicitadoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setFocusable(false);
        jScrollPane3.setViewportView(jTable1);

        jLabel29.setText("Seleccione el cliente ");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable2.setFocusable(false);
        jScrollPane6.setViewportView(jTable2);

        jLabel30.setText("Seleccione el evento");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jButtonAgregarEventoSolicitado)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonListarEventoSolicitado)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEliminarEventoSolicitado))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFechaHora, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(txtEventoSeleccionado)
                                    .addComponent(txtClienteEventoSolicitado))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtEliminarEveFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(6, 6, 6)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(txtClienteEventoSolicitado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(txtEventoSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(txtFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarEventoSolicitado)
                    .addComponent(jButtonListarEventoSolicitado)
                    .addComponent(jButtonEliminarEventoSolicitado)
                    .addComponent(txtEliminarEveFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Abrir");

        jMenuItem1.setText("SALIR");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void listarDatosClientes() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("RUT");
        modelo.addColumn("Nombre");
        jTable1.setModel(modelo);
        
        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
           @Override
           public void valueChanged(ListSelectionEvent e) {
               if (!e.getValueIsAdjusting()) {
                   int selectedRow = jTable1.getSelectedRow();
                   if (selectedRow != -1) {
                       // Obtener los datos de la fila seleccionada
                       String rut = jTable1.getValueAt(selectedRow, 0).toString();
                       String nombre = jTable1.getValueAt(selectedRow, 1).toString();
                       // Mostrar los datos en el JTextField o en otro componente
                       txtClienteEventoSolicitado.setText(rut);
                   }
               }
           }
       });
        
        String datos[] = new String [6];

        for(Cliente c: col.listarClientes()) {
            datos[0]= c.getRut();
            datos[1]= c.getNombreCompleto();
            modelo.addRow(datos);
            jTable1.setModel(modelo);
        }
        
    }
    
    private void listarDatosPaqueteEvento() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("id_evento");
        modelo.addColumn("tipo evento");
        jTable2.setModel(modelo);
        
        jTable2.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
           @Override
           public void valueChanged(ListSelectionEvent e) {
               if (!e.getValueIsAdjusting()) {
                   int selectedRow = jTable2.getSelectedRow();
                   if (selectedRow != -1) {
                       // Obtener los datos de la fila seleccionada
                       String idEvento = jTable2.getValueAt(selectedRow, 0).toString();
                       String tipoEvento = jTable2.getValueAt(selectedRow, 1).toString();
                       // Mostrar los datos en el JTextField o en otro componente
                       txtEventoSeleccionado.setText(idEvento);
                   }
               }
           }
       });
        
        
        String datos[] = new String [6];

        for(PaqueteEvento pqEvento: col.listarPaqueteEvento()) {
            datos[0]= String.valueOf(pqEvento.getIdEvento());
            datos[1]= pqEvento.getTipoEvento();String.valueOf(pqEvento.getIdEvento());
            modelo.addRow(datos);
            jTable2.setModel(modelo);
        }
        
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButtonEliminarEventoSolicitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarEventoSolicitadoActionPerformed
        // TODO add your handling code here:
        if (txtEliminarEveFechaHora.getText().trim().isEmpty()) {
            jTextArea4.setText("Debes ingresar fecha y hora del evento "
                + "en el mismo formato que se muestra por pantalla  "
                + "\npara eliminar el evento solicitado");
        }else{
            col.eliminarEventoSolicitado(txtEliminarEveFechaHora.getText());
            jTextArea4.setText("presione listar para ver la Eliminacion del evento");
        }
    }//GEN-LAST:event_jButtonEliminarEventoSolicitadoActionPerformed

    private void jButtonListarEventoSolicitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarEventoSolicitadoActionPerformed
        // TODO add your handling code here:
        jTextArea4.setText(col.listarEventos());
    }//GEN-LAST:event_jButtonListarEventoSolicitadoActionPerformed

    private void jButtonAgregarEventoSolicitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarEventoSolicitadoActionPerformed
        // TODO add your handling code here:
        String rutBuscado = txtClienteEventoSolicitado.getText();
        Cliente cliente = new Cliente();
        for(Cliente c: col.listarClientes()) {
            if (c.getRut().equals(rutBuscado)) {
                cliente = c;
            }
        }
       
        boolean isMatrimonio = false;
        int id_evento_Buscado = Integer.parseInt(txtEventoSeleccionado.getText());
        Fiesta fiestas = new Fiesta ();
        Matrimonio matrimonio = new Matrimonio();
        for(PaqueteEvento pqEvent: col.listarPaqueteEvento()) {
            if (pqEvent.getIdEvento()== (id_evento_Buscado)) {
                if(pqEvent.getTipoEvento().equals("matrimonio")){
                    isMatrimonio = true;

                    matrimonio = new Matrimonio(txtTiempoCantPlatos.getText(), Boolean.parseBoolean(txtMusicaEnVivo.getText()), pqEvent.getIdEvento(), pqEvent.getTipoEvento(), pqEvent.getDescripcionEvento(), pqEvent.getCantidadAsistentes(), pqEvent.getTamanioRecinto(), pqEvent.getCantidadMesas(), pqEvent.getPrecio());
                }else{
                    fiestas = new Fiesta (Boolean.parseBoolean(txtConOsinAlcohol.getText()), Integer.parseInt(txtNroDjs.getText()), pqEvent.getIdEvento(), pqEvent.getTipoEvento(), pqEvent.getDescripcionEvento(), pqEvent.getCantidadAsistentes(), pqEvent.getTamanioRecinto(), pqEvent.getCantidadMesas(), pqEvent.getPrecio());
                }
            }   
        }

        Evento evento = new Evento(cliente, isMatrimonio ? matrimonio : fiestas, txtFechaHora.getText());
        col.agregarEvento(evento, jTextArea4);
    }//GEN-LAST:event_jButtonAgregarEventoSolicitadoActionPerformed

    private void jButtonEliminarPaqEventoFiestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarPaqEventoFiestaActionPerformed
        // TODO add your handling code here:
        if (txtEliminarPaqEventFiesta.getText().trim().isEmpty()) {
            jTextArea2.setText("Campo vacio debes ingresar el id del evento antes de intentar eliminar");
        }else{
            if (col.eliminarPaqueteEvento(Integer.parseInt(txtEliminarPaqEventFiesta.getText())) == true){
                jTextArea2.setText("Evento Eliminado, presione listar Evento para visualizar la eliminacion");
            }else{
                jTextArea2.setText("no se encontro el evento para Eliminar");
            }
        }
    }//GEN-LAST:event_jButtonEliminarPaqEventoFiestaActionPerformed

    private void jButtonListarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarEventoActionPerformed
        // TODO add your handling code here:
        jTextArea2.setText(col.listarRegPaqueteEventos());
    }//GEN-LAST:event_jButtonListarEventoActionPerformed

    private void jButtonAgregarFiestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarFiestaActionPerformed
        // TODO add your handling code here:
        Fiesta fiestas = new Fiesta
        (Boolean.parseBoolean(txtConOsinAlcohol.getText()),Integer.parseInt(txtNroDjs.getText()),0,txtTipoEvento.getText(),txtDesEveneto.getText(), Integer.parseInt(txtCantidadAsistentes.getText()), Double.parseDouble(txtTamanioRecinto.getText()), Integer.parseInt(txtCantidadMesas.getText()), Double.parseDouble(txtPrecio.getText()));

        col.agregarRegPaqueteEventos(fiestas,jTextArea2);
        listarDatosPaqueteEvento();
    }//GEN-LAST:event_jButtonAgregarFiestaActionPerformed

    private void jButtonListarEventoMatriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarEventoMatriActionPerformed
        // TODO add your handling code here:
        jTextArea2.setText(col.listarRegPaqueteEventos());
    }//GEN-LAST:event_jButtonListarEventoMatriActionPerformed

    private void jButton7AgregarMatrimonioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7AgregarMatrimonioActionPerformed
        // TODO add your handling code here:
        Matrimonio matrimonio = new Matrimonio
        (txtTiempoCantPlatos.getText(), Boolean.parseBoolean(txtMusicaEnVivo.getText()), 0,txtMatriTipoEvento.getText(),txtMatriDesEveneto.getText(), Integer.parseInt(txtMatriCantAsistentes.getText()), Double.parseDouble(txtMatriTamanioRecinto.getText()), Integer.parseInt(txtMatriCantMesas.getText()), Double.parseDouble(txtMatriPrecio.getText()));

        col.agregarRegPaqueteEventos(matrimonio,jTextArea2);
        
        listarDatosPaqueteEvento();
    }//GEN-LAST:event_jButton7AgregarMatrimonioActionPerformed

    private void txtModificarNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarNombreClienteActionPerformed

    private void jButtonModificarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarTelefonoActionPerformed
        // TODO add your handling code here:
        if (txtBuscarCliente.getText().trim().isEmpty()) {
            jTextArea5.setText("Debes buscar el rut del cliente antes de intentar modificar");
        }else{
            col.modificarTelefonoCliente(txtBuscarCliente.getText(), Integer.parseInt(txtModificarTelefono.getText()));
            jTextArea5.setText("presione listar para ver la modificacion");
        }
        col.buscarCliente(txtBuscarCliente.getText());
    }//GEN-LAST:event_jButtonModificarTelefonoActionPerformed

    private void jButton7ModificarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ModificarCorreoActionPerformed
        // TODO add your handling code here:
        if (txtBuscarCliente.getText().trim().isEmpty()) {
            jTextArea5.setText("Debes buscar el rut del cliente antes de intentar modificar");
        }else{
            col.modificarCorreoCliente(txtBuscarCliente.getText(), txtModificarCorreo.getText());
            jTextArea5.setText("presione listar para ver la modificacion");
        }
    }//GEN-LAST:event_jButton7ModificarCorreoActionPerformed

    private void jButtonModificarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarNombreActionPerformed
        // TODO add your handling code here:
        if (txtBuscarCliente.getText().trim().isEmpty()) {
            jTextArea5.setText("Debes buscar el rut del cliente antes de intentar modificar");
        }else{
            col.modificarNombreCliente(txtBuscarCliente.getText(), txtModificarNombreCliente.getText());
            jTextArea5.setText("presione listar para ver la modificacion");
        }
    }//GEN-LAST:event_jButtonModificarNombreActionPerformed

    private void jButtonModificarRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarRutActionPerformed
        // TODO add your handling code here:
        if (txtBuscarCliente.getText().trim().isEmpty()) {
            jTextArea5.setText("Debes buscar el rut del cliente antes de intentar modificar");
        }else{
            col.modificarRutCliente(txtBuscarCliente.getText(), txtModificarRut.getText());
            jTextArea5.setText("presione listar para ver la modificacion");
        }
    }//GEN-LAST:event_jButtonModificarRutActionPerformed

    private void jButtonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarClienteActionPerformed
        // TODO add your handling code here:
        if (txtEliminarCliente.getText().trim().isEmpty()) {
            jTextArea5.setText("Campo vacio debes ingresar el rut del cliente antes de intentar elinimar");
        }else{
            if (col.eliminarCliente(txtEliminarCliente.getText()) == true){
                jTextArea5.setText("Cliente Eliminado, presione listar para comprobar la eliminacion");
            }else{
                jTextArea5.setText("no se encontro el rut para Eliminar el Cliente");
            }
        }
    }//GEN-LAST:event_jButtonEliminarClienteActionPerformed

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        // TODO add your handling code here:
        if (txtBuscarCliente.getText().trim().isEmpty()) {
            jTextArea5.setText("Campo vacio debes ingresar el rut del cliente antes de intentar Buscar");
        }else{
            if (col.buscarCliente(txtBuscarCliente.getText()) == true){
                jTextArea5.setText("cliente encontrado" + col.mostrarDatosCliente(txtBuscarCliente.getText()));
            }else{
                jTextArea5.setText("no se logro encontrar");
            }
        }
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jButtonLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarCamposActionPerformed
        // TODO add your handling code here:
        txtBuscarCliente.setText("");
        txtCantidadAsistentes.setText("0");
        txtCantidadMesas.setText("0");
        txtClienteEventoSolicitado.setText("");
        txtConOsinAlcohol.setText("Responde true o false");
        txtCorreo.setText("");
        txtDesEveneto.setText("fiesta 15");
        txtEliminarCliente.setText("0");
        txtEventoSeleccionado.setText("");
        txtFechaHora.setText("0");
        txtMatriCantAsistentes.setText("0");
        txtMatriCantMesas.setText("0");
        txtMatriDesEveneto.setText("matrimonio full");
        txtMatriPrecio.setText("0");
        txtMatriTamanioRecinto.setText("0");
        txtMatriTipoEvento.setText("matrimonio");
        txtMusicaEnVivo.setText("Responde true o false");
        txtNombreCompleto.setText("");
        txtNroDjs.setText("0");
        txtPrecio.setText("0");
        txtRut.setText("");
        txtTamanioRecinto.setText("0");
        txtTelefono.setText("0");
        txtTiempoCantPlatos.setText("");
        txtTipoEvento.setText("fiesta");
        jTextArea1.setText("");
        jTextArea2.setText("");
        jTextArea4.setText("");
        jTextArea5.setText("");
        txtEliminarPaqEventFiesta.setText("0");
        txtModificarRut.setText("Ingresa 9 o 10 caracteres");

    }//GEN-LAST:event_jButtonLimpiarCamposActionPerformed

    private void jButtonListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarClienteActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(col.listarRegistroCliente());
    }//GEN-LAST:event_jButtonListarClienteActionPerformed

    private void jButtonAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarClienteActionPerformed

        try {
            Cliente cliente = new Cliente(txtRut.getText(), txtNombreCompleto.getText(), txtCorreo.getText(), Integer.parseInt(txtTelefono.getText()));
            if (cliente.validarLargoRut()) {
                if (cliente.validarLargoTelefono()) {
                    col.agregarRegistroCliente(cliente, jTextArea1);
                } else {
                    jTextArea1.setText("Debes agregar 9 numeros para agregar el telefono");
                }
            } else {
                jTextArea1.setText("El RUT no es valido debes agregar entre 9 a 10 caracteres.");
            }
        } catch (NumberFormatException e) {
            jTextArea1.setText("El campo de telefono debe ser un valor numerico.");
        }
        
        listarDatosClientes();
    }//GEN-LAST:event_jButtonAgregarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroClienteEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroClienteEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroClienteEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroClienteEvento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroClienteEvento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton7AgregarMatrimonio;
    private javax.swing.JButton jButton7ModificarCorreo;
    private javax.swing.JButton jButtonAgregarCliente;
    private javax.swing.JButton jButtonAgregarEventoSolicitado;
    private javax.swing.JButton jButtonAgregarFiesta;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonEliminarCliente;
    private javax.swing.JButton jButtonEliminarEventoSolicitado;
    private javax.swing.JButton jButtonEliminarPaqEventoFiesta;
    private javax.swing.JButton jButtonLimpiarCampos;
    private javax.swing.JButton jButtonListarCliente;
    private javax.swing.JButton jButtonListarEvento;
    private javax.swing.JButton jButtonListarEventoMatri;
    private javax.swing.JButton jButtonListarEventoSolicitado;
    private javax.swing.JButton jButtonModificarNombre;
    private javax.swing.JButton jButtonModificarRut;
    private javax.swing.JButton jButtonModificarTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtCantidadAsistentes;
    private javax.swing.JTextField txtCantidadMesas;
    private javax.swing.JTextField txtClienteEventoSolicitado;
    private javax.swing.JTextField txtConOsinAlcohol;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDesEveneto;
    private javax.swing.JTextField txtEliminarCliente;
    private javax.swing.JTextField txtEliminarEveFechaHora;
    private javax.swing.JTextField txtEliminarPaqEventFiesta;
    private javax.swing.JTextField txtEventoSeleccionado;
    private javax.swing.JTextField txtFechaHora;
    private javax.swing.JTextField txtMatriCantAsistentes;
    private javax.swing.JTextField txtMatriCantMesas;
    private javax.swing.JTextField txtMatriDesEveneto;
    private javax.swing.JTextField txtMatriPrecio;
    private javax.swing.JTextField txtMatriTamanioRecinto;
    private javax.swing.JTextField txtMatriTipoEvento;
    private javax.swing.JTextField txtModificarCorreo;
    private javax.swing.JTextField txtModificarNombreCliente;
    private javax.swing.JTextField txtModificarRut;
    private javax.swing.JTextField txtModificarTelefono;
    private javax.swing.JTextField txtMusicaEnVivo;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtNroDjs;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRut;
    private javax.swing.JTextField txtTamanioRecinto;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTiempoCantPlatos;
    private javax.swing.JTextField txtTipoEvento;
    // End of variables declaration//GEN-END:variables
}
